"""Molecular Descriptor Lists for Chemical Analysis

This module defines comprehensive lists of molecular descriptors used throughout
the ReactivityRatios project for chemical data analysis and machine learning.

The descriptors are organized into categories:
- DFT descriptors: Quantum chemical properties from density functional theory
- RDKit descriptors: Molecular descriptors computed by RDKit
- Buried volume descriptors: Steric environment descriptors
- General molecular information: Basic molecular identifiers

These lists are used to:
1. Define feature sets for machine learning models
2. Validate data completeness in datasets
3. Generate descriptor subsets for specific analyses
4. Ensure consistency across different parts of the pipeline
"""

# List of all potential keys that could be added to result_dict
dft_size_shape = [
    'AtomNum',
    'Weight',
    'Farthest_Distance',
    'Mol_Radius',
    'Mol_Sizes',
    'MPP',
    'SDP',
    'Volume',
    'Density',
    "Mol_Size_Short",
    "Mol_Size_2",
    "Mol_Size_L",
    "Length_Ratio",
    "Len_Div_Diameter",]

dft_els_prop = [
    'Dipole_Moment',
    'Quadrupole_Moment',
    'Octopole_Moment',
    'Nu',
    'Pi',
    'MPI',]

dft_surface = [
    'ESPmin',
    'ESPmax',
    'Overall_Surface_Area',
    'Pos_Surface_Area',
    'Neg_Surface_Area',
    'Overall_Average',
    'Pos_Average',
    'Neg_Average',
    'Overall_Variance',
    'Nonpolar_Area',
    'Polar surface area',
    'ALIEmin',
    'ALIEmax',
    'ALIE_Ave',
    'ALIE_Var',
    'LEAmin',
    'LEAmax',
    'LEA_Ave',
    'LEA_Var',]

dft_FMO = [
    # For non-radical cases
    "ODI_HOMO_1",
    "ODI_HOMO",
    "ODI_LUMO",
    "ODI_LUMO_Add1",
    "ODI_Mean",
    "ODI_Std",
    "HOMO_1",
    "HOMO",
    "LUMO",
    "LUMO_Add1",
    
    # For radical cases
    "ODI_HOMO_a",
    "ODI_HOMO_b", 
    "ODI_LUMO_a",
    "ODI_LUMO_b",
    "HOMO_a",
    "HOMO_b",
    "LUMO_a",     
    "LUMO_b"]

rdkit_descriptors = [
    # 2D descriptors
    'MaxAbsEStateIndex',
    'MaxEStateIndex',
    'MinAbsEStateIndex',
    'MinEStateIndex',
    'qed',
    'SPS',
    'MolWt',
    'HeavyAtomMolWt',
    'ExactMolWt',
    'NumValenceElectrons',
    'NumRadicalElectrons',
    'MaxPartialCharge',
    'MinPartialCharge',
    'MaxAbsPartialCharge',
    'MinAbsPartialCharge',
    'FpDensityMorgan1',
    'FpDensityMorgan2',
    'FpDensityMorgan3',
    'BCUT2D_MWHI',
    'BCUT2D_MWLOW',
    'BCUT2D_CHGHI',
    'BCUT2D_CHGLO',
    'BCUT2D_LOGPHI',
    'BCUT2D_LOGPLOW',
    'BCUT2D_MRHI',
    'BCUT2D_MRLOW',
    'AvgIpc',
    'BalabanJ',
    'BertzCT',
    'Chi0',
    'Chi0n',
    'Chi0v',
    'Chi1',
    'Chi1n',
    'Chi1v',
    'Chi2n',
    'Chi2v',
    'Chi3n',
    'Chi3v',
    'Chi4n',
    'Chi4v',
    'HallKierAlpha',
    'Ipc',
    'Kappa1',
    'Kappa2',
    'Kappa3',
    'LabuteASA',
    'PEOE_VSA1',
    'PEOE_VSA10',
    'PEOE_VSA11',
    'PEOE_VSA12',
    'PEOE_VSA13',
    'PEOE_VSA14',
    'PEOE_VSA2',
    'PEOE_VSA3',
    'PEOE_VSA4',
    'PEOE_VSA5',
    'PEOE_VSA6',
    'PEOE_VSA7',
    'PEOE_VSA8',
    'PEOE_VSA9',
    'SMR_VSA1',
    'SMR_VSA10',
    'SMR_VSA2',
    'SMR_VSA3',
    'SMR_VSA4',
    'SMR_VSA5',
    'SMR_VSA6',
    'SMR_VSA7',
    'SMR_VSA8',
    'SMR_VSA9',
    'SlogP_VSA1',
    'SlogP_VSA10',
    'SlogP_VSA11',
    'SlogP_VSA12',
    'SlogP_VSA2',
    'SlogP_VSA3',
    'SlogP_VSA4',
    'SlogP_VSA5',
    'SlogP_VSA6',
    'SlogP_VSA7',
    'SlogP_VSA8',
    'SlogP_VSA9',
    'TPSA',
    'EState_VSA1',
    'EState_VSA10',
    'EState_VSA11',
    'EState_VSA2',
    'EState_VSA3',
    'EState_VSA4',
    'EState_VSA5',
    'EState_VSA6',
    'EState_VSA7',
    'EState_VSA8',
    'EState_VSA9',
    'VSA_EState1',
    'VSA_EState10',
    'VSA_EState2',
    'VSA_EState3',
    'VSA_EState4',
    'VSA_EState5',
    'VSA_EState6',
    'VSA_EState7',
    'VSA_EState8',
    'VSA_EState9',
    'FractionCSP3',
    'HeavyAtomCount',
    'NHOHCount',
    'NOCount',
    'NumAliphaticCarbocycles',
    'NumAliphaticHeterocycles',
    'NumAliphaticRings',
    'NumAromaticCarbocycles',
    'NumAromaticHeterocycles',
    'NumAromaticRings',
    'NumHAcceptors',
    'NumHDonors',
    'NumHeteroatoms',
    'NumRotatableBonds',
    'NumSaturatedCarbocycles',
    'NumSaturatedHeterocycles',
    'NumSaturatedRings',
    'RingCount',
    'MolLogP',
    'MolMR',
    'fr_Al_COO',
    'fr_Al_OH',
    'fr_Al_OH_noTert',
    'fr_ArN',
    'fr_Ar_COO',
    'fr_Ar_N',
    'fr_Ar_NH',
    'fr_Ar_OH',
    'fr_COO',
    'fr_COO2',
    'fr_C_O',
    'fr_C_O_noCOO',
    'fr_C_S',
    'fr_HOCCN',
    'fr_Imine',
    'fr_NH0',
    'fr_NH1',
    'fr_NH2',
    'fr_N_O',
    'fr_Ndealkylation1',
    'fr_Ndealkylation2',
    'fr_Nhpyrrole',
    'fr_SH',
    'fr_aldehyde',
    'fr_alkyl_carbamate',
    'fr_alkyl_halide',
    'fr_allylic_oxid',
    'fr_amide',
    'fr_amidine',
    'fr_aniline',
    'fr_aryl_methyl',
    'fr_azide',
    'fr_azo',
    'fr_barbitur',
    'fr_benzene',
    'fr_benzodiazepine',
    'fr_bicyclic',
    'fr_diazo',
    'fr_dihydropyridine',
    'fr_epoxide',
    'fr_ester',
    'fr_ether',
    'fr_furan',
    'fr_guanido',
    'fr_halogen',
    'fr_hdrzine',
    'fr_hdrzone',
    'fr_imidazole',
    'fr_imide',
    'fr_isocyan',
    'fr_isothiocyan',
    'fr_ketone',
    'fr_ketone_Topliss',
    'fr_lactam',
    'fr_lactone',
    'fr_methoxy',
    'fr_morpholine',
    'fr_nitrile',
    'fr_nitro',
    'fr_nitro_arom',
    'fr_nitro_arom_nonortho',
    'fr_nitroso',
    'fr_oxazole',
    'fr_oxime',
    'fr_para_hydroxylation',
    'fr_phenol',
    'fr_phenol_noOrthoHbond',
    'fr_phos_acid',
    'fr_phos_ester',
    'fr_piperdine',
    'fr_piperzine',
    'fr_priamide',
    'fr_prisulfonamd',
    'fr_pyridine',
    'fr_quatN',
    'fr_sulfide',
    'fr_sulfonamd',
    'fr_sulfone',
    'fr_term_acetylene',
    'fr_tetrazole',
    'fr_thiazole',
    'fr_thiocyan',
    'fr_thiophene',
    'fr_unbrch_alkane',
    'fr_urea',
    # 3D descriptors
    'PMI1',
    'PMI2',
    'PMI3',
    'NPR1',
    'NPR2',
    'RadiusOfGyration',
    'InertialShapeFactor',
    'Eccentricity',
    'Asphericity',
    'SpherocityIndex',
    'PBF']

reac_BV_descriptors = [
    "react_atom_serial",
    "Buried_Volume"
]

general_mol_info = [
    'smiles',
    # 'Morgan_Fingerprint', # You could, but not super convenient with parquet. Could be generated in-situ with smiles
]

dft_descriptors = dft_surface + dft_size_shape + dft_els_prop + dft_FMO